export { default as Hero } from '@/app/components/sections/Hero';
export { default as ProofBand } from '@/app/components/sections/ProofBand';
export { default as FeaturedProjects } from '@/app/components/sections/FeaturedProjects';
export { default as Services } from '@/app/components/sections/Services';
export { default as StackReasons } from '@/app/components/sections/StackReasons';
export { default as ContactCta } from '@/app/components/sections/ContactCta';
export { default as Projects } from '@/app/components/sections/Projects';
export { default as Skills } from '@/app/components/sections/Skills';
export { default as Contact } from '@/app/components/sections/Contact';
