-- ============================================================
-- projects
-- ============================================================
create table public.projects (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null,
  image       text not null default '',
  tags        text[] not null default '{}',
  link        text not null default '',
  github      text not null default '',
  featured    boolean not null default false,
  created_at  timestamptz not null default now()
);

alter table public.projects enable row level security;

-- ============================================================
-- skills
-- ============================================================
create table public.skills (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category    text not null,
  icon        text not null,
  description text,
  "order"     integer not null default 0
);

alter table public.skills enable row level security;

-- ============================================================
-- profile (single-row table)
-- ============================================================
create table public.profile (
  id         boolean primary key default true check (id),
  name       text not null,
  title      text not null,
  bio        text not null,
  email      text not null,
  phone      text not null default '',
  location   text not null default '',
  github     text not null default '',
  linkedin   text not null default '',
  twitter    text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.profile enable row level security;

-- ============================================================
-- contact_messages
-- ============================================================
create table public.contact_messages (
  id            bigint generated by default as identity primary key,
  name          text not null,
  email         text not null,
  message       text not null,
  status        text not null default 'new' check (status in ('new', 'read', 'replied')),
  reply_message text,
  replied_at    timestamptz,
  created_at    timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

-- ============================================================
-- admin_auth (single-row override table — DB hash wins over ADMIN_PASSWORD_HASH env)
-- ============================================================
create table public.admin_auth (
  id                   boolean primary key default true check (id),
  admin_password_hash  text not null,
  updated_at           timestamptz not null default now()
);

alter table public.admin_auth enable row level security;

-- ============================================================
-- two_factor (per-email row)
-- ============================================================
create table public.two_factor (
  email        text primary key,
  enabled      boolean not null default false,
  secret       text,
  backup_codes text[],
  enabled_at   timestamptz
);

alter table public.two_factor enable row level security;

-- ============================================================
-- audit_logs
-- ============================================================
create table public.audit_logs (
  id          bigint generated always as identity primary key,
  timestamp   timestamptz not null default now(),
  user_id     text not null,
  action      text not null,
  resource    text not null,
  resource_id text,
  details     jsonb,
  ip          text,
  user_agent  text,
  success     boolean not null
);

create index audit_logs_timestamp_idx on public.audit_logs (timestamp desc);
create index audit_logs_action_idx on public.audit_logs (action);
create index audit_logs_resource_idx on public.audit_logs (resource);

alter table public.audit_logs enable row level security;

-- ============================================================
-- Helpers pour resynchroniser les séquences d'identité après le
-- seed unique (scripts/migrate-to-supabase.ts), qui insère des IDs
-- explicites au lieu de laisser `generated always as identity` générer.
-- ============================================================
create function public.setval_projects_id_seq() returns void as $$
begin
  perform setval(pg_get_serial_sequence('public.projects', 'id'), coalesce((select max(id) from public.projects), 1));
end;
$$ language plpgsql security definer;

create function public.setval_skills_id_seq() returns void as $$
begin
  perform setval(pg_get_serial_sequence('public.skills', 'id'), coalesce((select max(id) from public.skills), 1));
end;
$$ language plpgsql security definer;
